name: Deploy to GitHub Pages

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main']

# Add concurrency settings
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'preview-${{ github.ref_name }}'
      url: '${{ steps.build-publish.outputs.page_url }}'
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: preview-out # change to your build folder
          build_command: |
            npm run build

            # Replace slashes with dashes in branch name
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              BRANCH_NAME="${{ github.head_ref }}"
            else
              BRANCH_NAME="${GITHUB_REF_NAME}"
            fi
            
            # Replace slashes with dashes for safety
            DEPLOY_PATH="${BRANCH_NAME//\//-}"
            echo "deploy_path=${DEPLOY_PATH}" >> $GITHUB_OUTPUT
            
            # Create preview directory structure
            mkdir -p "preview-out/${DEPLOY_PATH}"
            cp -r dist/* "preview-out/${DEPLOY_PATH}/"
            
            # Copy 404.html to root for routing
            cp dist/404.html preview-out/


      - name: Comment on PR
        # if: |
        #   github.event_name == 'pull_request' && 
        #   steps.deploy.conclusion == 'success' && 
        #   steps.wait-for-pages.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🎉 **Preview Deployed!**
              👉 <a href="${{ steps.build-publish.outputs.page_url }}/${{ steps.build-publish.outputs.deploy_path }}" target="_blank">View Preview</a>`
            })
